### ISSUE TITLE
getting median fees efficiently 

### ISSUE THREAD

**Issue by svewa** [ksedgwic/clboss#100]
I have a strong feeling that I'm missing something, but my C++ skills are horrible, so I'm just gonna ask here:

Boss/Mod/PeerCompetitorFeeMonitor/Surveyor.cpp get's the weighted median for fees for a peer.
it makes one call "listchannels source=PEERID" (line 44) and adds all relevant SCIDs to a stack (line 55).

then it recursively iterates the stack, calling "listchannel scid=SCID) for each element, then figuring out the right direction because it usually get's 2 channels for each SCID, and then it adds the base/proportional fee to some object that eventually gives the weighted median.

as my node has 185 peers with a total of 21634 (x2 directional) channels, this results in 21635 calls to "listchannels scid=SCID" for me. This runs for about 20 minutes.

And I just wonder why not initially make the call "listchannels destination=PEERID" and feed the output directly (minus our own channel) into the median thingy, saving the parsing of 20k channels and 21450 RPC calls? besides switching source/destinatin in the call, it only does one call per peer that is done now, too. I'd guess this should be over in seconds.

**Comment by ZmnSCPxj** [comment]
The `destination` parameter was added in June 2021, so some older `lightningd` do not support it.  I would recommend waiting for June 2022, just to be a little more sure that most users have upgraded to a versions that *does* have `destination`.
