### ISSUE TITLE
Error while installing on raspiblitz

### ISSUE THREAD

**Issue by RemoRitzmann** [ksedgwic/clboss#102]
Problem:
checking whether make sets $(MAKE)... (cached) yes
./configure: line 15966: syntax error near unexpected token `:,'
./configure: line 15966: `AX_PTHREAD(:,'

I did:
cd /home/bitcoin/cl-plugins-available/plugins
sudo git clone https://github.com/ZmnSCPxj/clboss.git
cd clboss
su
autoreconf -i
./configure && make && sudo make install

2nd Problem:
root@raspberrypi:/home/bitcoin/cl-plugins-available/plugins/clboss# sudo apt install autotools # nogo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package autotools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'autotools' has no installation candidate

**Comment by ZmnSCPxj** [comment]
Can you try using the official tarball? https://github.com/ZmnSCPxj/clboss/releases/download/0.11D/clboss-0.11D.tar.gz

From the official tarball, just `./configure && make`.

In particular, if building from github checkout, you need `autoconf-archive`, which might not come standard in your RaspPi OS repos.

**Comment by RemoRitzmann** [comment]
Thanks, it now works. I installed all this and tried again. 
sudo apt install build-essential
sudo apt install pkg-config
sudo apt install libev-dev
sudo apt install libcurl4-gnutls-dev
sudo apt install libsqlite3-dev
sudo apt install dnsutils
sudo apt install autoconf-archive
sudo apt install autotools # nogo
sudo apt install git
sudo apt install automake
sudo apt install libtool

**Comment by ZmnSCPxj** [comment]
Hi Remo, see also section "Dependencies" in `README.md` https://github.com/ZmnSCPxj/clboss#dependencies

**Comment by RemoRitzmann** [comment]
I saw: You can then add a plugin=/path/to/clboss or important-plugin=/path/to/clboss setting to your C-Lightning configuration file.

I added
plugin=/home/bitcoin/cl-plugins-available/plugins/clboss
to
sudo nano /home/bitcoin/.lightning/config
and 
restart lightning-cli
but then lightning-cli does not start anymore.

how can I make sure clboss is running? Ex with:
admin@IP:~ ₿ lightning-cli clboss-status
{
   "code": -32601,
   "message": "Unknown command 'clboss-status'"

**Comment by devastgh** [comment]
I compiled 0.11D from the tarball on ubuntu 20.04. Did not do "make install", just replaced the clightning plugin path with the new executable. C-lightning 0.10.2 failed to start with this version, going back to 0.11C started ok.

**Comment by ZmnSCPxj** [comment]
Can you get the `lightningd` logs on 0.11D?  Could it be related to #101 ?

**Comment by devastgh** [comment]
> Can you get the `lightningd` logs on 0.11D? Could it be related to #101 ?

Yes it must be that, i'm using clboss-zerobasefee option in my config.
edit: I'm compiling 0.11E from git master now, i'll report back in a couple of minutes.

**Comment by bastelpingu** [comment]
0.11D runs with me under ubuntu 20.04

had to comment out min-onchain but that was already fixed =)

**Comment by devastgh** [comment]
> > Can you get the `lightningd` logs on 0.11D? Could it be related to #101 ?
> 
> Yes it must be that, i'm using clboss-zerobasefee option in my config. edit: I'm compiling 0.11E from git master now, i'll report back in a couple of minutes.

Clboss 0.11E is working ok for me, with the zerobasefee option. I think #101 fixed my issue as well.

**Comment by ZmnSCPxj** [comment]
Okthx, there are some additional commits as well but they only trigger on `make check` on some edge-case systems.

**Comment by ZmnSCPxj** [comment]
Hi @RemoRitzmann , are you using Raspiblitz?  In that case, you should probably not mess with the config files, but enable CLBOSS in the Blitz configuration.  To get the latest version, you can modify `/home/admin/config.scripts/cl-plugin.clboss.sh` to change the `CLBOSSVERSION` line to `CLBOSSVERSION="0.12"`.  See also https://github.com/rootzoll/raspiblitz/pull/3080

**Comment by ZmnSCPxj** [comment]
Is this still relevant?

**Comment by RemoRitzmann** [comment]
Sorry, I could not give it a try, because my node needs to reindex, I'm now at 93% but it takes ages on raspiblitz. So yes, I run raspiblitz. My question is how I can configure clboss. I will try your tip "modify /home/admin/config.scripts/cl-plugin.clboss.sh to change the CLBOSSVERSION line to CLBOSSVERSION="0.12". See also https://github.com/rootzoll/raspiblitz/pull/3080" when I'm back online. So I'll come back to this in a weeks time for closure, hopefully.

**Comment by RemoRitzmann** [comment]
Hi @ZmnSCPxj I'm back online and tried to run the script, but I think that was the wrong way:
admin@IP:~ ₿ python3 /home/admin/config.scripts/cl-plugin.clboss.sh
  File "/home/admin/config.scripts/cl-plugin.clboss.sh", line 8
    if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "-help" ];then
         ^
SyntaxError: invalid syntax

How can I check the actual CLBOSSVERSION? I used raspiblitz menu update functions but I can not verify.

**Comment by 3cola** [comment]
Are you trying to execute a bash script with python ?

On June 8, 2022 7:16:13 PM GMT+02:00, Remo Ritzmann ***@***.***> wrote:
***@***.***:~ ₿ python3 /home/admin/config.scripts/cl-plugin.clboss.sh

**Comment by RemoRitzmann** [comment]
You are right. 
./home/admin/config.scripts/cl-plugin.clboss.sh on mainnet
works much better :-)
