### ISSUE TITLE
Switch to disable rebalancer/initial rebalancer

### ISSUE THREAD

**Issue by devastgh** [ksedgwic/clboss#108]
Is it possible to either introduce a switch that disables all rebalancers globally, or at least the initialrebalancer?
Or clboss-unmanage have a "rebalance" switch that does disable all rebalances for a channel?

Rationale: Initial rebalancer is doing serious damage here, from multiple point of views:
- currently i have to disable clboss alltogether if i want to do a ln+ circular swap with free rebalance.
- It makes very very high cost decisions. My last initial rebalance event was done at ~12673ppm. It should have sane limits about a rebalance economical viability. If it's unsure, it's better to do nothing, and leave the channel unbalanced than to burn that much.

**Comment by ZmnSCPxj** [comment]
What version are you using? 0.10 is known to be too aggressive, and it has been toned down in 0.11x series

**Comment by devastgh** [comment]
> What version are you using? 0.10 is known to be too aggressive, and it has been toned down in 0.11x series

I'm running 0.11E version, but i observed roughly the same behaviour with 0.11C too.

**Comment by ZmnSCPxj** [comment]
I have some initial work in a branch somewhere which should help make `InitialRebalancer` select the destination based on cheapness of route, and similarly for `JitRebalancer`.  This would be post-0.12, though.

Probably can do the unmanage for rebalancings, though again, post 0.12.

**Comment by devastgh** [comment]
Thanks!
The unmanage option would be useful perpetually for triangle/circle swaps.
