### ISSUE TITLE
Check clboss version

### ISSUE THREAD

**Issue by pratapc65** [ksedgwic/clboss#109]
How do I know what version of clboss is executed with cln . 
I tried clboss --version but I do not get the clboss version.

**Comment by ZmnSCPxj** [comment]
`clboss --version` should work.  If you are in the build directory with the `clboss` binary, then `./clboss --version` will work.  For more accurate information, see the C-Lightning logs --- there should be an entry much like:

```log
2022-04-25T11:52:01.526Z INFO    plugin-clboss: clboss 0.11E
```

**Comment by pratapc65** [comment]
Thanks.
