### ISSUE TITLE
Unknown command 'clboss-zerobasefee=require

### ISSUE THREAD

**Issue by pratapc65** [ksedgwic/clboss#110]
Hello Team, 
I run CLBOSS 0.11E & CLN 0.11 in a docker and when I execute command clboss-zerobasefee=require the error unkonwn command is displayed. 
clboss-status command works fine .

**Comment by willcl-ark** [comment]
`clboss-zerobasefee=require` is a configuration option, not a command.

Pass it to lightningd as an argument or put it in your lightningd configuration file and restart lightningd for it to take effect.

**Comment by pratapc65** [comment]
I tried to pass it as an argument to lightningd  dc exec lightningd lightning-cli clboss-zerobasefee=require and get unknown command. 
Please let me know how to pass it as an argument to lightningd.

**Comment by willcl-ark** [comment]
Pass it as it's written in the [documentation](https://github.com/ZmnSCPxj/clboss#--clboss-zerobasefeerequireallowdisallow): `--clboss-zerobasefee=require`

**Comment by pratapc65** [comment]
I run dc exec lightningd lightning-cli --clboss-zerobasefee=require and get the error " lightning-cli: --clboss-zerobasefee=require: unrecognized option"

**Comment by ZmnSCPxj** [comment]
The option is intended to be passed to `lightningd`, ***not*** `lightning-cli`.

How are you starting the `lightningd` daemon?  Do you use `crontab`?  A SystemD `.service`?  A shell script?  That is what you need to modify to add this option.

**Comment by pratapc65** [comment]
I run the lightningd daemon in a docker container . How can I add it as part of lightningd container.

**Comment by ZmnSCPxj** [comment]
I am not sure, since I do not use Docker.  Presumably you modified *something* in your docker to add a `--plugin=/path/to/clboss`.  That is what you should modify to add `--clboss-zerobasefee=require`.  Or if you had a `config` file that you added `plugin=/path/to/clboss` then you need to also modify that file to add `clboss-zerobasefee=require`

**Comment by pratapc65** [comment]
Thanks, I have updated the  config file to include zerobasefee and is working as expected.
