### ISSUE TITLE
clboss-unmanage crashes

### ISSUE THREAD

**Issue by jayrockk** [ksedgwic/clboss#111]
admin@192.168.0.1:~ ₿ lightning-cli clboss-unmanage 
03875ae1688cf675f22b1386a595e1b4bb0e2065526ea876dc505fea2085233885
{
   "code": -4,
   "message": "Plugin terminated before replying to RPC call."
}
admin@192.168.0.1:~ ₿ lightning-cli clboss-status
{
   "code": -32601,
   "message": "Unknown command 'clboss-status'"
}

In cl.log:

`2022-04-30T10:35:56.851Z UNUSUAL plugin-clboss: Killing plugin: JSON-RPC response "id"-field is not a u64
`

restarting lightningd: clboss is back, said channel is still in the 'unmanaged' list

Version 0.11E

EDIT:

This time, after running the same command a after restarting lightning (using up-key in the terminal):

admin@192.168.0.149:~ ₿ lightning-cli clboss-unmanage 03875ae1688cf675f22b1386a595e1b4bb0e2065526ea876dc505fea2085233885
{
   "code": -32602,
   "message": "Parameter error: Incorrect type.",
   "data": {}
}

clboss is still alive. I did see the crash several times before, though.

**Comment by ZmnSCPxj** [comment]
Hmm, strange error.  CLBOSS handles the `id` field properly, this was a bug before (#47) where it was translated through `double` but it should not be the case now.

Could you try this?

* Execute CLBOSS directly on the commandline: e.g. `./clboss` or wherever you have the `clboss` binary.
* Input this exactly: `{"id": 18446744073709551615, "method": "getmanifest", "params": {}}` then press Enter.
* Press Ctrl-D to exit.

If it returns a long response with `"id": 18446744073709551615` then your CLBOSS should be compiled correctly and with the proper handling for 64-bit `id`.

**Comment by jayrockk** [comment]
Here you go:

admin@192.168.0.1:/home/bitcoin/cl-plugins-available/clboss-0.11E ₿ sudo ./clboss
DiG 9.16.22-Debian
{"id": 18446744073709551615, "method": "getmanifest", "params": {}}
{"jsonrpc": "2.0", "id": 18446744073709551615, "result": {"dynamic": true, "hooks": ["htlc_accepted", "rpc_command"], "subscriptions": ["channel_opened", "channel_state_changed", "connect", "disconnect", "forward_event", "sendpay_failure", "sendpay_success"], "rpcmethods": [{"name": "clboss-dowser", "usage": "fromid toid", "description": "Execute the dowsing algorithm to estimate the useful capacity between two nodes.", "deprecated": false}, {"name": "clboss-earnings-rebalancer", "usage": "", "description": "Debug command to trigger EarningsRebalancer module.", "deprecated": false}, {"name": "clboss-externpay", "usage": "payment_hash", "description": "Inform CLBOSS that a future `pay` command with the given `payment_hash` is controlled by a third party that might have incentive to damage the metrics of our peers. Relevant only to custodial services.", "deprecated": false}, {"name": "clboss-findbypopularity", "usage": "", "description": "Trigger ChannelFinderByPopularity algorithm.", "deprecated": false}, {"name": "clboss-ignore-onchain", "usage": "[hours]", "description": "Ignore onchain funds for {hours} (default 24 hours).", "deprecated": false}, {"name": "clboss-movefunds", "usage": "amount sourcenode destnode feebudget", "description": "Move {amount} from a channel with {sourcenode} to a channel with {destnode}, with no more than {feebudget}.  {amount} and {feebudget} must have 'msat' suffixes, and {sourcenode} and {destnode} must be node IDs.  THIS COMMAND IS FOR DEBUGGING CLBOSS AND SHOULD NOT BE USED FOR MANUAL MANAGEMENT.", "deprecated": false}, {"name": "clboss-notice-onchain", "usage": "", "description": "Cancel previous clboss-ignore-onchain and resume managing onchain funds.", "deprecated": false}, {"name": "clboss-status", "usage": "", "description": "Get CLBOSS status.", "deprecated": false}, {"name": "clboss-swaps", "usage": "", "description": "Report about offchain-to-onchain swaps", "deprecated": false}, {"name": "clboss-unmanage", "usage": "nodeid tags", "description": "Specify that a {nodeid} will not be fully managed by CLBOSS, disabling the management of {tags}.", "deprecated": false}], "options": [{"name": "clboss-auto-close", "type": "bool", "default": false, "description": "Whether CLBOSS should automatically close bad channels (EXPERIMENTAL).  Set 'true' to enable, 'false' to disable."}, {"name": "clboss-max-channel", "type": "string", "default": 16777215, "description": "Maximum size of channels to make."}, {"name": "clboss-min-channel", "type": "string", "default": 500000, "description": "Minimum size of channels to make."}, {"name": "clboss-min-onchain", "type": "string", "default": 30000, "description": "Target to leave this number of satoshis onchain, putting the rest into channels."}, {"name": "clboss-zerobasefee", "type": "string", "default": "allow", "description": "Whether to require, allow, or disallow a 0 base fee."}]}}
`

**Comment by ZmnSCPxj** [comment]
Well, the output does show a `"id": 18446744073709551615` so it looks like it should be OK.  Can you monitor and check if it happens again?  Maybe gremlins?  You are sure the same `clboss` binary is the one that is in `/home/bitcoin/cl-plugins-available/clboss-0.11E` right? (Looks like a raspiblitz setup so it should be right?)

**Comment by jayrockk** [comment]
Hi,

1. yes, Raspíblitz setup

2. yes, I still get  the same message
admin@192.168.0.1:~ ₿  lightning-cli clboss-unmanage 03875ae1688cf675f22b1386a595e1b4bb0e2065526ea876dc505fea2085233885
{
   "code": -32602,
   "message": "Parameter error: Incorrect type.",
   "data": {}
}


3. yes, the binary is the same -  compare with path in the previous message:
admin@192.168.0.1:~ ₿ ls -al /home/bitcoin/cl-plugins-enabled/clboss
lrwxrwxrwx 1 root root 54 May  1 05:53 /home/bitcoin/cl-plugins-enabled/clboss -> /home/bitcoin/cl-plugins-available/clboss-0.11E/clboss

I can't figure out what's going on :-(

**Comment by ZmnSCPxj** [comment]
The message `"Parameter error: Incorrect type"` means you are missing the second argument to `clboss-unmanage`, a string with comma-separated tags:

* `close` do not close channels with this node.
* `open` do not open channels to the node
* `lnfee` do not set channel fee to this node.

To re-enable management of a node, you specify an empty string explicitly like `clboss-unmanage 03875ae1688cf675f22b1386a595e1b4bb0e2065526ea876dc505fea2085233885 ""`.  If you want to unmanage all the current tags: `clboss-unmanage 03875ae1688cf675f22b1386a595e1b4bb0e2065526ea876dc505fea2085233885 open,close,lnfee`.

What I was asking is if there is a repeat of `JSON-RPC response "id"-field is not a u64`

**Comment by jayrockk** [comment]
All right, got it. Confirmed that the second argument works as expected.

No,  JSON-RPC response "id"-field is not a u64 did not appear anymore.

**Comment by ZmnSCPxj** [comment]
Okay, if you see it again please inform me, but if not, I will close this after a week, is that OK?

**Comment by jayrockk** [comment]
Sure, let's do it like this.

**Comment by ZmnSCPxj** [comment]
Been past a week, so.... closing.
