### ISSUE TITLE
Libgcrypt crashes on startup

### ISSUE THREAD

**Issue by bubelov** [ksedgwic/clboss#131]
I've noticed that clboss 0.13A fails to start after reboot, any ideas why?

![Screenshot from 2022-05-27 14-08-00](https://user-images.githubusercontent.com/1189245/170651167-6440cb7f-2beb-4a74-81ca-d3b86c06740a.png)

**Comment by ZmnSCPxj** [comment]
That seems a very strange error, possibly from `libcurl`? Hmm.

**Comment by bubelov** [comment]
It was installed via this script:

https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/cl-plugin.clboss.sh

The script itself looks fine, but I don't see any error handling there. It could be due to unhandled apt install error or something. Anyway, I tried re-running the same script and clboss seems to be working fine after reboots

Closing it since I'm not sure if the required deps were satisfied
