### ISSUE TITLE
"Can't recover from plugin failure, terminating."

### ISSUE THREAD

**Issue by AndiMacTen** [ksedgwic/clboss#151]
Hi,
I moved my CLN node to another computer. Therefore I copied the .lightning folder to the new installation and the node came up successfully again.
After installing clboss, it seems clboss is preventing the cln daemon to start again. Sadly there is not much logs I could share.

From the cli 
`$ lightningd --daemon `
`Can't recover from plugin failure, terminating.`

Debug (log-level=debug
log-level=debug:plugin-clboss)

`DEBUG   lightningd: Opened log file /home/username/.lightning/debug.log`
`DEBUG   plugin-manager: started(9086) /usr/local/libexec/c-lightning/plugins/autoclean`
`DEBUG   plugin-manager: started(9087) /usr/local/libexec/c-lightning/plugins/chanbackup`
`DEBUG   plugin-manager: started(9088) /usr/local/libexec/c-lightning/plugins/bcli`
`DEBUG   plugin-manager: started(9089) /usr/local/libexec/c-lightning/plugins/commando`
`DEBUG   plugin-manager: started(9090) /usr/local/libexec/c-lightning/plugins/fetchinvoice`
`DEBUG   plugin-manager: started(9091) /usr/local/libexec/c-lightning/plugins/funder`
`DEBUG   plugin-manager: started(9092) /usr/local/libexec/c-lightning/plugins/topology`
`DEBUG   plugin-manager: started(9093) /usr/local/libexec/c-lightning/plugins/keysend`
`DEBUG   plugin-manager: started(9094) /usr/local/libexec/c-lightning/plugins/offers`
`DEBUG   plugin-manager: started(9095) /usr/local/libexec/c-lightning/plugins/pay`
`DEBUG   plugin-manager: started(9096) /usr/local/libexec/c-lightning/plugins/txprepare`
`DEBUG   plugin-manager: started(9097) /usr/local/libexec/c-lightning/plugins/spenderp`
`DEBUG   plugin-manager: started(9098) /usr/local/libexec/c-lightning/plugins/cln-grpc`
`DEBUG   plugin-manager: started(9100) /usr/local/libexec/c-lightning/plugins/bookkeeper`
`DEBUG   plugin-manager: started(9101) /usr/local/bin/clboss`
`UNUSUAL plugin-clboss: Killing plugin: timed out before replying to getmanifest`
`DEBUG   lightningd: io_break: check_plugins_manifests`

I renamed the data.clboss and keys.clboss files but with no effect.

Only difference, old machine was cln release v0.12.0, the new installation is on cln current master (v0.12.0-106-g37c07dd).

Any idea what this issue could caused by and how ti get clboss running again?
 Thank you!

**Comment by tsjk** [comment]
I think I stumbled upon this as well. See https://gitlab.com/bitcoin/gentoo/-/issues/11, which I just wrote.

**Comment by tsjk** [comment]
`PLUGIN_MANIFEST_TIMEOUT` is defined in `lightningd/plugin.c` . Have you tried increasing that?

**Comment by AndiMacTen** [comment]
thanks for bringing this up.
I increased that value by 10x, unfortunately with the same result as before.

**Comment by tsjk** [comment]
Was just a guess. But, that would have been too easy. I for one downgraded. Hopefully someone with some better knowledge of the code bases can give us a hint before we need to delve into it ourselves.

**Comment by tsjk** [comment]
I do wonder... What if you don't load the plugin at start, but load it after core-lightning has booted and is operational? I'll try that when I have time.

**Comment by tsjk** [comment]
> I do wonder... What if you don't load the plugin at start, but load it after core-lightning has booted and is operational? I'll try that when I have time.

That didn't work either.

**Comment by grubles** [comment]
Running into the same issue when starting CLN (at commit 62bfed9a8df8731be44ba4e86afb08a5d28a4442):

```
UNUSUAL plugin-clboss: Killing plugin: timed out before replying to getmanifest
```

**Comment by jonasnick** [comment]
Same here (CLN 22.11rc2)

**Comment by cdecker** [comment]
The problem has been addressed on the CLN side for now by making the switch to non-numeric JSON-RPC calls go through the deprecation cycle: https://github.com/ElementsProject/lightning/pull/5727

Notice that this will temporarily allow clboss to use the numeric IDs, until they get removed in about 6 months time, so not a permanent fix, but should bridge the gap until clboss adds support for non-numeric IDs.

**Comment by tsjk** [comment]
I think this can be closed now.

**Comment by cdecker** [comment]
I don't think so: CLN added the nonnumeric ids as a temporary fix, deprecating numeric-only IDs. This means that after the deprecation cycle in ~6months we'll be facing the same issue again, unless clboss adds support for non-numeric IDs.

You can test support by starting lightningd with `--allow-deprecated-apis=false` and you'll see what lightningd expects after enforcing current deprecations

**Comment by tsjk** [comment]
Yes ok. It needs a new release. But the latest head is fixed. I think.

**Comment by AndiMacTen** [comment]
closed
