### ISSUE TITLE
clboss no longer managing fees after upgrading core lightning to v23

### ISSUE THREAD

**Issue by dazl** [ksedgwic/clboss#159]
clboss has been managing outgoing fees on my channels for over a year but as of a couple of weeks ago fees never change (unless I adjust them manually with setchannel).

The timing appears to coincide with the upgrade of core lightning to v23.02.2

Running 0.13A

(also: before stopping adjusting fees some channels were set to unusually high ppm, in the thousands of msats where they typically would have been set in the hundreds)

**Comment by xNDTyf** [comment]
I can confirm this correlation wit 23.2, but ZmnSCPxj seems to be no more active .. (Satoshi 2.0?)

**Comment by dazl** [comment]
Thank you for confirming. I have been looking for alternative fee management scripts for core lightning but have not found anything so far

**Comment by xNDTyf** [comment]
I use https://github.com/lightningd/plugins/tree/master/feeadjuster in parallel to clboss, for feemod. 
Use feeadjuster-feestrategy=median ! The other setting does not "work", or does not help for this purpose.

I think it is just a small modification that is needed to the clboss api call, but I am unable to modify without debugging and I have only time for "looking in the code"

**Comment by dazl** [comment]
ah yes thanks for the tip on feeadjuster-feestrategy. 

I'll try it again with that setting. I also need to figure out why it does not read my feeadjuster-exclude.list

**Comment by ksedgwic** [comment]
I think it is quite likely that #162 fixes this.  I think I see CLBOSS managing fees on my nodes that are using that fix.

**Comment by ksedgwic** [comment]
@dazl @xNDTyf Any chance you could re-check with current master?  I'm not sure if my use on testnet is sensitive enough to fee issues to confirm ...

**Comment by chrisguida** [comment]
This is the last issue before release, correct? Seems like if no one can repro this soon, it could just go into the next release?

**Comment by ksedgwic** [comment]
I'm pretty sure that CLBOSS is managing fees on my 23.08 testnet nodes.

I think we should close this issue and re-open it with new information / symptoms if necessary.

**Comment by btchans** [comment]
` plugin-clboss: FeeModderBySize: Peer xxxx has 29 other peers, 7 of which have less capacity than us, 22 have more.  Multiplier: 0.719958
 `
i get those messages. so i assume clboss is feemodding by size. not by balance.
any chance to explain the difference?
how to switch from "bySize" to "byBalance"?
how do they get triggered or to configure?

**Comment by ksedgwic** [comment]
I don't know.

The message above makes me think "size" means total capacity of the peer.  Is that what you think?  And which/what balance do you mean?

**Comment by tsjk** [comment]
Was it ever byBalance?
