### ISSUE TITLE
CLBOSS needs a release

### ISSUE THREAD

**Issue by ksedgwic** [ksedgwic/clboss#172]
- [x] What should the release number be?
- [x] Update the `Changelog`
- [x] Validate on important CLN versions (23.08 is validated)
- [x] Are all modifications since last release appropriate / stable?  Do any need to be "gated/enabled"?
- [x] Marked https://github.com/ZmnSCPxj/clboss/issues/159 as closed pending additional symptoms/info

**Comment by tsjk** [comment]
Considering that there are issues labelled with milestones, setting a version number that reflects which have been reached and which not would make sense.

**Comment by tsjk** [comment]
I now run ef5c41612da0d544b0ed1f3e986b4b07126723a1 on my CLN v23.05.2.
If I don't complain within the near future it can be assumed that all is ok.

**Comment by JaviLib** [comment]
Good idea, I'm testing it in my node. So far so good.

**Comment by vincenzopalazzo** [comment]
>Considering that there are issues labelled with milestones, setting a version number that reflects which have been reached and which not would make sense.

I feel that with the change in maintenance, there is also a change in priority, so I will skip it for now the roadmap and rebuild it on top of our priority

>What should the release number be?

I guess we can keep the same version and to a 14-rc1? I would like to change only the A/B prefix because I do not know what these means, but maybe I am missing something around

> Validate on important CLN versions (23.08 is validated)

Till now no complaining, so I guess we can safely assume that we are ready to go for a rc version?

> Are all modifications since last release appropriate / stable? Do any need to be "gated/enabled"?

I will reconsider (for not now, maybe for the next cln release) how we can use splice and if there are any logic of clboss that with slice is outdated

**Comment by ksedgwic** [comment]
Based on history the `0.13A` and `0.13B` are heading for `0.13` (which wasn't released yet

I prefer the numbered rc as well.  Should we use `v0.13rc2` and then `v0.13` so we don't have a missing release?

Are we ready to tag?

**Comment by vincenzopalazzo** [comment]
>I prefer the numbered rc as well. Should we use v0.13rc2 and then v0.13 so we don't have a missing release?

It make sense to me Ken, lets go for v0.13rc2

> Are we ready to tag?

No crash on my nodes, so we are ready to tag IMHO

**Comment by ksedgwic** [comment]
I created #174 to capture additional `CHANGELOG.md` (note filename change) entries.

**Comment by tsjk** [comment]
One thing I for one would appreciate is a spelled out range of CLN versions a particular clboss release has been tested with.
CLN is still shaky ground, and I think people running clboss would prefer planning CLN/clboss upgrades to avoid needing to deal with broken version combinations.

**Comment by ksedgwic** [comment]
@tsjk I'm trying to be careful about claiming CLBOSS is tested.  The best I can do personally right now is report which version combinations appear to be working for me.  I think it is critical that users of CLBOSS be extra careful/cautious/defensive.

I think CLBOSS works for me on `testnet` with CLN `v23.05` and `v23.08`

**Comment by chrisguida** [comment]
Looks like this one is done! Excellent work, gentlemen!!! :rocket:

**Comment by ksedgwic** [comment]
Closing, completed
