### ISSUE TITLE
Avoid planning channels to nodes with similar IP addresses

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#18]
If possible we should channel to nodes with different geographical locations based on published IP address, in order to avoid having all our channels going to various LNBIG nodes.

This requires a map of autonomous system numbers to IP addresses.

LNBIG is known to host multiple nodes in various locations but hopefully this reduces the probability of having all our channels to LNBIG.

For .onion:

* Give each unique .onion its own bucket?
* Put all .onion in a single unique bucket, but allow drawing more than one from that bucket?
  * Equivalently, create N buckets for .onions and throw onions randomly in one of the onion buckets.

Not sure at what point to implement this.  Probably best is to have the `ChannelCandidateInvestigator` add this as an investigation as well, and to penalize candidates that happen to have IPs similar to higher-scored candidates.

IRC discussion with @willcl-ark and @darosior :

```
<willcl_ark> zmnscpxj_: CLBOSS seemed to cope ok even during that crazy fee market. It did open two channels (when I had zero) at a rate of 250s/vB (two in one transaction), but then seemed to "wait" until fees were lower again to open a further 5. I suppose because of how agnositc it is, 5 out of 7 channels are to various LNBIG nodes which is probably not ideal, but difficult to automatically bucket peers by "likely same 
<willcl_ark> owner"
<zmnscpxj_> Yes, if a majority of your funds is outside of channels, CLBOSS will put as much as possible into channels even if feerates are high
<zmnscpxj_> but it tries to hold off as much as it can until feerates go low
<willcl_ark> That is pretty much exactly what I saw
<zmnscpxj_> works as designed then
<willcl_ark> :)
<zmnscpxj_> TheBlueMatt has suggested IP binning before (in the context of routing, but still...) so it might be useful to consider that as well
<zmnscpxj_> in order to avoid the "everryone is LNBIG in purgatory"
<willcl_ark> TBH, looks like the LNBIG nodes are hosted in different locations (on 1ML) so not sure that will help
<zmnscpxj_> awww crap
<willcl_ark> you could base it on Alias, but that's easy to break too
<zmnscpxj_> yes
<zmnscpxj_> and using IP binning does not help with .onion as well
<willcl_ark> actually I am not correct, all the LNBIG nodes I partnered with appear to be (Ashburn, VA, United States)
<willcl_ark> might be worth to have it "just in case", even if it's not perfect, I don't think it would make anything worse
<zmnscpxj_> okay, looks like IP binning might be useful at least to *reduce* the possibility
<willcl_ark> exactly
<zmnscpxj_> Dunno what to do about .onion though, oh well
<zmnscpxj_> And I have to wonder about IPv6 as well
<darosior> asmap ?
<zmnscpxj_> what is asmap?
<darosior> bitcoind's new technique to make sybil connections more costy but that may be nonsensical for your matter
<zmnscpxj_> references?
<darosior> https://github.com/bitcoin/bitcoin/issues/16599
<zmnscpxj_> yes, TheBlueMatt has also suggested this for LN routing as well
<zmnscpxj_> though he suggests all .onion should go into a single bin, which worries me
<willcl_ark> You could allow more from the tor bin, than other bins?
<zmnscpxj_> could be done as well.
```

**Comment by willcl-ark** [comment]
FWIW here is an example of what my CLBOSS test set up for me -- very nicely balanced etc., but I think would be much improved by some simple bucketing logic:

```
my_address=xxxxxxx...xxx@xx.xx.xx.xx
num_utxos=1
utxo_amount=x.xxxxxxxxbtc (USD $x.xx)
num_channels=7
num_connected=7
num_gossipers=3
avail_out=xx.xxbtc (USD $xx.xx)
avail_in=xx.xxbtc (USD $xx.xx)
channels_flags=P:private O:offline
channels=

├x.xxxxbtc    OUT/OURS ┼ IN/THEIRS   x.xxxxbtc┤ SCID           FLAG AVAIL ALIAS
           ├───────────┼───────────────┤        YYYYYYxYYYYxY  [__] 100%  LNBIG.com [lnd-25]
├──────────────────────┼────┤                   YYYYYYxYYYYxY  [__] 100%  LNBIG.com [lnd-13]
                    ├──╢                        YYYYYYxYYYYxY  [__] 100%  rompert.com🔵
              ├────────┼──┤                     YYYYYYxYYYYxY  [__] 100%  LNBIG.com [lnd-05]
                     ├─┼┤                       YYYYYYxYYYYxY  [__] 100%  LNBIG.com [lnd-11]
                    ├──┼─┤                      YYYYYYxYYYYxY  [__] 100%  Leetning.com #1 SWE
                    ├──┼┤                       YYYYYYxYYYYxY  [__] 100%  LNBIG.com [lnd-17]
```

**Comment by willcl-ark** [comment]
Hey @ZmnSCPxj do you have plans to try and implement some IP (or similar) bucketing?

I closed all my channels during low on-chain fee market just to take advantage of it, but have to say that even with an "uneven" channel distribution CLBOSS just worked™ very well without any management. I didn't have that many forwards, but to be fair it was more than I had when I manually opened channels previously and I was well setup for general personal usage.

If you're not planning to implement this feature in the near future, I'll be happy to re-run latest master without bucketing and with a bit more balance and see how it gets on again...

**Comment by ZmnSCPxj** [comment]
Certainly, though not quite sure how to go about it yet.  Sorry for the delay in reply, things have been hectic in my non-Bitcoin activities, including a broken server whose parts I am finding difficult to find, bleah.

**Comment by ZmnSCPxj** [comment]
https://bitcoincore.reviews/16702.html for reference.

Important points:

* Bitcoin core supports an ASMAP, but does not come bundled with one yet.  Users are supposed to either create an ASMAP of their own somehow (instructions are unclear even to the reviewers) or just download from sipa, who is always 100% trustable and has never made a mistake, not even in bech32: https://github.com/sipa/asmap/demo.map
* Bitcoin ASMAP format is based on a video codec.  This means we have to reimplement or copy the Bitcoin ASMAP loading code.  Copying it is somewhat difficult as it might be dependent on other Bitcoin code.
* Tor .onions are hard to unsybil, as .onions are "free".  Suggestion is to reduce the number of buckets that .onions use, which makes them very unlikely to be channeled with.

**Comment by ZmnSCPxj** [comment]
Here is the correct link to `demo.map`: https://github.com/sipa/asmap/raw/master/demo.map

I am uncertain as to what is the ultimate source of `demo.map`.  Geolite2 database has a CC-BY-SA license, the /sipa/asmap repo has no license information, not sure whether the `demo.map` comes from the Geolite2 database.

Given an `ASMap` object that maps IP addresses to ASNs, what do we do?

So let us describe how CLBOSS decides channel creation.  First, a bunch of heuristics select candidate nodes for channeling.  Then the nodes go through `ChannelCandidateInvestigator`, which over time checks for uptime of the candidate nodes.

When we notice we have onchain funds that need to go into channels, we get the list of "good" nodes from `ChannelCandidateInvestigator`, which puts high-uptime, earlier-found nodes first in the list.

Currently, we prioritize assigning channels according to the order of this list.  The `ChannelCreator::Planner` module takes this list of nodes.

What we could do instead:

* Get ASNs of our current peers and put into a mapping from ASN to number-of-nodes-with-that-ASN.
* Initialize an empty mapping from number-of-nodes-in-ASN to an ordered list-of-nodes.
* For each node in the `ChannelCandidateInvestigator` list:
  * Get its ASN.
  * Look up the number-of-nodes-with-this-ASN (0 if not found).
  * Look up the appropriate list-of-nodes from the number-of-nodes-in-ASN.
  * Append the node to the found list-of-nodes.
  * Increment the number-of-nodes-with-this-ASN.
* Initialize an empty ordered list-of-nodes
* For each list-of-nodes in the number-of-nodes-in-ASN to list-of-nodes mapping:
  * Append the list-of-nodes to the current list-of-nodes.
* Return the list-of-nodes.

The returned list-of-nodes will then prioritize nodes that do not have the same ASN as current peers or higher-ranked candidates, and de-prioritzes nodes that have the same ASN as current peers or higher-ranked candidates.  This list of nodes is then what we pass to `ChannelCreator::Planner`.

**Comment by willcl-ark** [comment]
> https://bitcoincore.reviews/16702.html for reference.
> 
> Important points:
> 
> * Bitcoin core supports an ASMAP, but does not come bundled with one yet.  Users are supposed to either create an ASMAP of their own somehow (instructions are unclear even to the reviewers) or just download from sipa, who is always 100% trustable and has never made a mistake, not even in bech32: https://github.com/sipa/asmap/demo.map
> * Bitcoin ASMAP format is based on a video codec.  This means we have to reimplement or copy the Bitcoin ASMAP loading code.  Copying it is somewhat difficult as it might be dependent on other Bitcoin code.
> * Tor .onions are hard to unsybil, as .onions are "free".  Suggestion is to reduce the number of buckets that .onions use, which makes them very unlikely to be channeled with.

I think the raw ASMAP file requires asking your ISP for a BGP dump which, as you allude to, is possible but certainly pretty unlikely for people to do...

As #bitcoin-core-dev is logged, I presume posting logs as a snippet here is also OK (query simply `asmap` w/ 5 lines of context):
[asmap.txt](https://github.com/ZmnSCPxj/clboss/files/5695509/asmap.txt). I might suggest parsing from the bottom upwards...

Perhaps asmap is overkill for this situation -- as you say, even asmap can be trivially overcome by using tor, so perhaps some simpler bucketing by IP address CIDR range might be preferable?

It would certainly help with LNBIG as they operate today; they have been kind enough to host all nodes on `46.229.xxx.xxx` and `213.174.xxx.xxx` from what I can roughly see. Having two connections to them would not be of great concern.

I do think asmap buckets are the most technically-correct solution that exists today, but I can't tell if the work required by the developer (and users?) of an asmap filter would be worth it if an adversary could trivially defeat it...

**Comment by ZmnSCPxj** [comment]
My understanding is that by BlueMatt it is better.  From what little I understand it seems to be feasible for somebody to generate an ASMAP that is then distributed to multiple users, much like how we have a set of hardcoded nodes in `ConnectFinderByHardcode`.

**Comment by willcl-ark** [comment]
https://github.com/ZmnSCPxj/clboss/issues/18#issuecomment-745229067

To me, a solution of this sort seems to make the most sense for CLBOSS ^

Edit: But like I mentioned above, I am a bit worried if implementation is difficult, that it can be so trivially routed around by an attacker with Tor. Also a dedicated attacker could trivially setup nodes on purposefully different ASs ...

If you asked me "should my autonomous lightning node software _prefer_ opening channels to a _more diverse_ set of peers on different ASs?" then I would instinctively answer yes.

**Comment by ZmnSCPxj** [comment]
For now, I plan to make an abstract interface to an `IPBinner` object:

```c++
class IPBinner {
public:
    virtual ~IPBinner() { }
    virtual
    IPBin get_bin_of(IPAddr const&) =0;
};
```

`IPBin` would be a 128-bitvector that is `LessThanComparable` and `Hashable` (so it can be used with `std::map`/`std::set`/`std::unordered_map`/`std::unordered_set`), and `IPAddr` would have variant types for `IPv4`, `IPv6`, and `Onion`.  A "true" ASMAP would use the ASN for the `IPBin`, filling upper bits with 0s.

Until then, we can make do with a submask /16 for `IPv4`, some kind of submask for `IPv6` (dunno, /48? /64? go dig the `bitcoind` code?) and maybe set a high bit somewhere in the `IPBin` to separate IPv4 from IPv6.

For Tor, we could do hashing of .onion addresses and extracting 1 or 2 bits so that it maps to an `IPBin` of 0xFFFFFFFFFFFFFFFC to 0xFFFFFFFFFFFFFFFF, so we allow up to 4 onions.  The hashing would be a keyed hash to reduce the ability of targeted attacks by onion-users; we already have a `keys.clboss` file that we use for interacting with Boltz, we can reuse that as the key in the hash, and we even have `Secp256k1::SignerIF::get_privkey_salted_hash` to allow a signer holding `keys.clboss` to provide a keyed hash --- we hash the .onion, then hash the hash with `get_privkey_salted_hash` then get 2 bits from the first byte of the result.  Thus as long as our `keys.clboss` file is private to us (it is stored right next to the `hsm_secret`, which has to be even more private anyway), targeted attacks would not be possible, onion-users would have to spam the .onion space, which would not be cheap on LN since LN public nodes have to commit some amount of channel space.  CLBOSS also does some filtering based on how much a node has locked in channels, so an onion-using attacker would need to commit something like 50 mBTC (LOL hahahaha) in various channels to have multiple nodes it controls pass that test, so I guess that helps somewhat against the ".onions are free!" problem.

Then at some point while constructing objects we just bind a concrete `IPBinner` that uses submasks as desribed above for now, and we can update it later to replace the `IPBinner` with a true ASMAP once `bitcoind` has settled on how to distribute the map files and we can steal their work easily.  The ASMAP concrete `IPBinner` would have to use the same treatment for Tor, though.

When checking a node, we would need to do a `listnodes` query, which returns a set of `"addresses"`.  We prefer IPv4, then IPv6, then finally Torv3 or Torv2.  Then we call into the `IPBinner` interface we got.

**Comment by ZmnSCPxj** [comment]
Looks like the first 3 or 4 bytes for IPv6 (/24 or /32 prefix length) would be a good bin, roughly comparable to /16 on IPv4.  Could not grok the `bitcoind` code enough to figure out what it uses.

Looks to me we can use `typedef std::uint64_t IPBin;` rather than invent a 128-bit number.  ASNs are 32-bit anyway, and if 32 bits is enough to naively bin IPv6, that may be good enough for now.
