### ISSUE TITLE
`std::size_t` compilation on MacOS

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#21]
From @hosiawak : https://gist.github.com/hosiawak/14e43d591878c613458857ef30607c50

`Bitcoin::varint` is properly defined for `std::uint64_t`, but in the failure in question, `len` is an `std::size_t`.  If `std::uint64_t` != `std::size_t`, then the compiler makes a conversion from `std::size_t` to `std::uint64_t`, which leads it to matching `std::uint64_t const&` instead of `std::uint64_t&`, which leads to `Bitcoin::varint` returning `Bitcoin::Detail::VarIntConst` instead of `Bitcoin::Detail::VarInt`.

To confirm, @hosiawak, can you compile and run this on your MacOS system?

```c++
#include<cstddef>
#include<cstdint>
#include<iostream>

int main() {
    std::cout << "sizeof(std::size_t): " << sizeof(std::size_t) << std::endl;
    std::cout << "sizeof(std::uint64_t): " << sizeof(std::uint64_t) << std::endl;
    return 0;
}
```

On my Linux box it gives 8 for both sizes, if `sizeof(std::size_t)` is 4 on your system I probably need to change every `std::size_t` that is used in `Bitcoin::varint` to `std::uint64_t` instead.

**Comment by hosiawak** [comment]
It's 8 for both as well:

```
$ ./a.out
sizeof(std::size_t): 8
sizeof(std::uint64_t): 8
```

**Comment by ZmnSCPxj** [comment]
Huh, weird then.  Hmmm.

How about this?  Does it print "matcing" in your MacOS?

```c++
#include<cstddef>
#include<cstdint>
#include<iostream>

template<typename T>
struct IsMatching {
        static
        char const* fun() {
                return "not matching";
        }
};
template<>
struct IsMatching<std::uint64_t> {
        static
        char const* fun() {
                return "matching";
        }
};

int main() {
        std::cout << IsMatching<std::size_t>::fun() << std::endl;
        return 0;
}
```

**Comment by hosiawak** [comment]
not matching

**Comment by ZmnSCPxj** [comment]
Right, so both of them are 8 bytes but are not "the same" type.  Possibly, "just" changing all instances of `std::size_t` used in `Bitcoin::varint` to `std::uint64_t` "should" fix this.

**Comment by hosiawak** [comment]
There's no `size_t` in either `Bitcoin/varint.cpp` or `Bitcoin/varint.hpp`. I can do a search and replace and recompile if you tell me which files to look at :)

**Comment by ZmnSCPxj** [comment]
Yes, that is the issue, it is the callers of `Bitcoin::varint` which use `std::size_t`, on the assumption that `std::size_t` is the same as `std::uint64_t`.

**Comment by ZmnSCPxj** [comment]
A similar issue pops up in Linux `armv7l` 32-bit.
