### ISSUE TITLE
Pedantry in FreeBSD compilation

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#22]
We trigger this error in FreeBSD: https://gist.github.com/hosiawak/fe6c2b213f8baa57d987c069de8c1114

Not sure how we can fix this without hacking the upstream library.  @hosiawak would you mind sending a copy of the `ev.h` file that is failing?

**Comment by ZmnSCPxj** [comment]
@hosiawak can you try as well to reconfigure with the addition of a `CXXFLAGS="-Wno-noexcept-type"` argument to `./configure` and compile again? https://github.com/ZmnSCPxj/clboss/files/5500503/clboss-missing-include-functional.tar.gz

**Comment by hosiawak** [comment]
Adding `CXXFLAGS="-Wno-noexcept-type"` to `./configure` helped to get past the `ev.h` error.

Now getting [sockaddr related errors](https://gist.github.com/hosiawak/ac63a2c5b1f262e894199913b1a68bf1).

The `/usr/local/include/ev.h` file from my system is [here](https://gist.github.com/hosiawak/bcd5521c93ccd0a9e70ebce5b6e6d1de)

**Comment by ZmnSCPxj** [comment]
Hmm, okay, I am tempted to just add `AM_CXXFLAGS = -Wno-noexcept-type`. However, since we are linking to a library provided by the system, it might not work later at link time.  On the other hand, we never actually ***call*** any of the functions the compiler is complaning about.

Thank you for your perseverance.  I will go fix the socket things, probably I am using Linuxisms here.

**Comment by ZmnSCPxj** [comment]
Fixed in #24
