### ISSUE TITLE
clboss process hanging around

### ISSUE THREAD

**Issue by hosiawak** [ksedgwic/clboss#26]
Stopping lightningd doesn't kill clboss process, after a few rounds of restarts I get multiple clboss processes all and loadavg 16:
```
# service lightningd stop
Stopping lightningd.
pay: Lost connection to the RPC socket.
Waiting for PIDS: 44953, 44953.
```

```
# ps xavf | grep boss
44960 RJ     1:45.50 127 105     109   88408  45884   - 11548 100.2  0.3 clboss
45084 R+J    0:00.00 127   0       0    6740   2280   -    96   0.0  0.0 grep boss
```

**Comment by ZmnSCPxj** [comment]
Well, `clboss` does not properly handle RPC socket being closed on us (which will happen when you force-close `lightningd`) and will infloop in that case.  Will go fix.
