### ISSUE TITLE
Remove libsodium dependency?

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#5]
We repack libsodium since it is a security-sensitive dependency and we want to be in control of it in case of upstream takeover, but on the other hand it is actually fairly well-supported amongst distros (so repacking might be actually too paranoiac).

Further, we only really use the below bits:

* Secure random number generation.
* Secure `memzero`.
* Constant-time `memcmp`.
* SHA256

libsodium is a fairly large library and we are not using a lot of it, so it might actually be better to remove it and source the bits elsewhere.

* Secure random number generation - copy from bitcoind?  Just get from `/dev/random`? (not like we will actually be ported to Windows anytime soon given C-Lightning architecture...)
* Secure `memzero` - dunno, implement from scratch?
* Constant-time `memcmp` - implement from scratch
* SHA256 - copy from bitcoind

**Comment by Saibato** [comment]
And think about an alternative single hash function. 
crypto_hash_sha256  LTM like sha256d?

let *impl point to an other by default?

**Comment by ZmnSCPxj** [comment]
We need compatibility with `bitcoind` and `lightningd`, so we need sha256 that is same as theirs.

**Comment by ZmnSCPxj** [comment]
Implemented: https://github.com/ZmnSCPxj/clboss/commit/8139afcaa79e5c820b4fb07e5581ee5aa461881e
