### ISSUE TITLE
Dig error as command missing when installed and in PATH for user on Debian

### ISSUE THREAD

**Issue by willcl-ark** [ksedgwic/clboss#58]
Followup from https://github.com/ZmnSCPxj/clboss/pull/52

I'm running clboss master at 18d1a09e9ff52b31df79347cd42b96b3ed79891a on Debian GNU/Linux bullseye/sid and see the follwing in the logs at startup:

```
... UNUSUAL plugin-clboss: DnsSeed: Cannot seed by DNS: `dig` command is not installed, it is usually available in a `dnsutils` package for your OS.
```

I run `lightningd` as user `bitcoin` who has dig installed and available:

```
bitcoin in ~/.lightning at will-nuc ➜ echo $SHELL
/usr/bin/fish

bitcoin in ~/.lightning at will-nuc ➜ whoami
bitcoin

bitcoin in ~/.lightning at will-nuc ➜ which dig
/usr/bin/dig

bitcoin in ~/.lightning at will-nuc ➜ dig -v; echo $status
DiG 9.16.8-Debian
0
```

Everything seems to be working, but odd error message I can't seem to get rid of nonetheless...

**Comment by willcl-ark** [comment]
I thought again of this issue because I noticed that https://github.com/ZmnSCPxj/clboss/commit/f4f0c80bc10499bb461e1cf4b68723de5ceba104 was patching over both people who do not have the `dig` command, and users like myself for whom clboss seems not to be able to find the system `dig`...

I run `lightningd` as user "bitcoin", who certainly has access to this installed command:

```bash
will in clboss at will-nuc on  master [$?] ➜ sudo runuser -l bitcoin -c 'dig -v'
DiG 9.18.1-1-Debian
```

I don't understand why [can_get()](https://github.com/ZmnSCPxj/clboss/blob/f4f0c80bc10499bb461e1cf4b68723de5ceba104/DnsSeed/get.cpp#L26-L33) is still failing... Any ideas?

It doesn't affect me in any way, just curious...

**Comment by ZmnSCPxj** [comment]
Can you check `which dig` result?  Also, try something like:

    `which dig` -v

Also:

    `sudo -u bitcoin dig -v
     sudo -u bitcoin which dig

**Comment by willcl-ark** [comment]
`which dig` actually causes some issues for me, as I'm using fish shell (which I think does not have the `which` command anymore, at least I have an abbreviation (like an alias) saved to `command -v`)...

`command -v dig` though (run as `will`, `bitcoin` or `su`) returns dig correctly, as does `sudo -u bitcoin dig -v`, so it's certainly in the same (dfefault) path for everyone:

```
/usr/bin/dig
```

Now I know this lookssuspiciously like my shell might be interfering, however we are never calling `which dig` ever AFAIK, so I don't think this should be an issue:

```C++
Ev::Io<std::string> can_get() {
	return Ev::runcmd("dig", {"-v"}).then([](std::string _) {
		return Ev::lift(std::string(""));
	}).catching<std::runtime_error>([](std::runtime_error const& _) {
		return Ev::lift(std::string(
			"`dig` command is not installed, it is usually "
			"available in a `dnsutils` package for your OS."
		));
	});
}

```

**Comment by ZmnSCPxj** [comment]
We *are* using `execvp` underneath `Ev::runcmd`, though, which is specced, and I quote:

> **p - execlp(), execvp(), execvpe()**
>> These  functions  duplicate  the actions of the shell in searching for an executable file if the specified filename does not contain a slash (/) character.

Maybe it is the "actions of the shell"?

Anyway, are you willing to try this patch?

```patch
diff --git a/Boss/Main.cpp b/Boss/Main.cpp
index ef11af5..61328b6 100644
--- a/Boss/Main.cpp
+++ b/Boss/Main.cpp
@@ -6,6 +6,7 @@
 #include"Boss/Mod/all.hpp"
 #include"Boss/Msg/Begin.hpp"
 #include"Boss/Shutdown.hpp"
+#include"Boss/log.hpp"
 #include"Ev/Io.hpp"
 #include"Ev/ThreadPool.hpp"
 #include"S/Bus.hpp"
@@ -112,6 +113,11 @@ public:
                                        );

                return Ev::yield().then([this]() {
+                       return Boss::log( *bus, Info
+                                       , "PATH = %s"
+                                       , getenv("PATH")
+                                       );
+               }).then([this]() {
                        /* Begin.  */
                        return bus->raise(Boss::Msg::Begin());
                }).then([this]() {
```

Apply with `patch -p1 < file-containing-that-patch` on the tarball expanded directory, recompile, then restart `lightningd`, it should print the `$PATH` environment variable that `clboss` experiences on the `lightning` log, at the info level (you can switch it to `Warn` or `Error` if you set your logs to filter out info level or below)..

**Comment by willcl-ark** [comment]
I applied the patch manually on top of master, which revealed the below, but did **not** raise the `dig` error subsequently:

``` log
2022-04-26T14:14:54.844Z INFO    plugin-clboss: PATH = /home/bitcoin/.pyenv/versions/lightningd-3.8.1/bin:$PATH
2022-04-26T14:15:05.044Z INFO    plugin-clboss: clboss 0.11E
2022-04-26T14:15:05.045Z INFO    plugin-clboss: PeerComplaintsDesk: Auto-close: enabled.
2022-04-26T14:15:05.045Z INFO    plugin-clboss: AmountSettingsHandler: Onchain reserve set by --clboss-min-onchain to 2000000 satoshis.
2022-04-26T14:15:05.045Z INFO    plugin-clboss: ChannelFeeManager: zerobasefee: allow
2022-04-26T14:15:05.138Z INFO    plugin-clboss: New block at 733645
2022-04-26T14:15:05.138Z INFO    plugin-clboss: Started.
2022-04-26T14:15:05.524Z INFO    plugin-clboss: InternetConnectionMonitor: online.
2022-04-26T14:15:05.526Z INFO    plugin-clboss: New block at 733646
2022-04-26T14:15:10.823Z INFO    plugin-clboss: PeerCompetitorFeeMonitor: Surveying 02113fba7b4a54068a335b2a042fd889138f6eb3c791eea6435e144cde90409d47 progress: 9/55 (0.163636)
...
```

Reverting the patch (back to master @ f4f0c80) instantly causes the error again:

```log
2022-04-26T14:18:06.931Z UNUSUAL plugin-clboss: DnsSeed: Cannot seed by DNS: `dig` command is not installed, it is usually available in a `dnsutils` package for your OS.
```

Now I am even more confused :P

edit: `pyenv which dig` also returns `/usr/bin/dig` so I don't think the lightning venv is messing it up either...

**Comment by ZmnSCPxj** [comment]
> I applied the patch manually on top of master, which revealed the below, but did **not** raise the `dig` error subsequently:

wut.

> ```log
> 2022-04-26T14:14:54.844Z INFO    plugin-clboss: PATH = /home/bitcoin/.pyenv/versions/lightningd-3.8.1/bin:$PATH
> ```

That is one helluva weird `$PATH`.  You expect only a "pure" `PATH`, one which has only `:`-separated directory names, and not a self-referential thing like that.  A `$PATH` here means something in the shell or in the invocation somewhere did not expand the previous `$PATH` fully, which might be the root cause of your problem.  Looks like shell shenanigans, maybe your shell startup script had too many escapes when it set the `PATH` environment variable?  With `getenv("PATH")` that broken, it looks like `execvp` is failing because of this?

**Comment by willcl-ark** [comment]
I think you're correct. Perhaps fish shell is evaluating the path later, or something I don't understand. Appears it shall remain a mystery anyway...

![image](https://user-images.githubusercontent.com/6606587/165359612-5aa67739-cbe8-45d6-9f84-739c6e156283.jpeg)

**Comment by ZmnSCPxj** [comment]
Hmmm.  `fish` says it is an "interactive" shell.  Maybe you have a different login shell vs system shell, and some files you changed for fish may also be in use by the system shell, which got confused due to `fish`-specific syntax?  How do you start `lightningd`?  Do you manage it with `crontab`, `systemd`, or something or other?  What is your `/bin/sh`?  Is it a link to `fish` or is it some other binary?

**Comment by willcl-ark** [comment]
Yep the issue was in systemd:

_/etc/system/systemd/lightningd.service_
```shell
[Service]
Environment="PATH=/home/bitcoin/.pyenv/versions/lightningd-3.8.1/bin:$PATH"
Environment="PYENV_VERSION=lightningd-3.8.1"
RuntimeDirectory="lightningd"
ExecStart=/usr/local/bin/lightningd --lightning-dir=/home/bitcoin/.lightning
```

Apparently `Environment` in a unit file does not expand env vars? Who knew (not me!)

Manually hardcoding the PATH seems to work, however I fixed my pyenv setup so I can remove the `PATH` environment line altogether, and now CLBOSS works flawlessly without that pesky Dig error!

Thanks for the help, even though it didn't turn out to stricly be related to CLBOSS :)

**Comment by ZmnSCPxj** [comment]
Okay, glad that was helpful!
