### ISSUE TITLE
Is it possible to make clboss use #zerobasefee for channels under some conditions?

### ISSUE THREAD

**Issue by GhostTyper** [ksedgwic/clboss#73]
There is this [#zerobasefee movement](https://www.reddit.com/r/Bitcoin/comments/opyxor/zerobasefee_please_reduce_your_nodes_base_fee_to/) to ease the lightning routing process. If I would like to participate in this with clboss: Is it possible to make clboss set the fees in some way so that it will use 0 base fee? Even though that this would diminish my earnings a little bit?

If not, I would like to make this as a feature request. The best way for me would be a configurable limit where clboss will set 0 base fee if the optimum base fee calculated by clboss is below. In this way clboss could honor #zerobasefee if other fees on the network would allow it with not too much "feeloss".

**Comment by ZmnSCPxj** [comment]
Yes, I do intend to add a `--clboss-zerobasefee=true` flag at some point.  Initially default false (since that is the current behavior) but will switch to default-true at some later release.

**Comment by ZmnSCPxj** [comment]
`--clboss-zerobasefee` now exists.  Closing.
