### ISSUE TITLE
Compilation failure on RaspiBlitz 1.7.1

### ISSUE THREAD

**Issue by jayrockk** [ksedgwic/clboss#90]
Based on the 0.11C tarball: When following the installation instructions, I have to run sudo autoreconf -i twice to get rid of the error in configure.ac:28.

```
admin@raspberrypi:/home/bitcoin/cl-plugins-available/clboss-0.11C $ sudo autoreconf -i
configure.ac:28: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
admin@raspberrypi:/home/bitcoin/cl-plugins-available/clboss-0.11C $ sudo autoreconf -i
admin@raspberrypi:/home/bitcoin/cl-plugins-available/clboss-0.11C $ 
```
After that, configure is created but fails:

```
.....
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
./configure: line 11415: AX_CXX_COMPILE_STDCXX_11: command not found
checking for gawk... (cached) gawk
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
./configure: line 11520: syntax error near unexpected token `:,'
./configure: line 11520: `AX_PTHREAD(:,'
```
I'm attaching configure (renamed to .txt) since I'm not an expert in the make tools. Any suggestions?

[configure.txt](https://github.com/ZmnSCPxj/clboss/files/7802683/configure.txt)

**Comment by hoplaaa** [comment]
I don't know if this can help, but you are not supposed to run autoreconf at all when building from the tarball: 
https://github.com/ZmnSCPxj/clboss#installing

I would try from scratch without running autoreconf.

**Comment by jayrockk** [comment]
Sorry, this doesn't help. There is no tarball for 11C.

**Comment by hoplaaa** [comment]
Can you have a look at #91 and #92 ?

**Comment by openoms** [comment]
> Sorry, this doesn't help. There is no tarball for 11C.

~~There is, but you need to go to the tags, not the releases:~~
~~https://github.com/ZmnSCPxj/clboss/releases/tag/0.11C~~

you can use the build in script to install script just edit the version and fix the link in https://github.com/rootzoll/raspiblitz/blob/4878730baba75ee3019a95d95cbc880f502a017d/home.admin/config.scripts/cl-plugin.clboss.sh#L37
(pay attention to the `v` before the version, but not before the tag also.)

edit: sorry commented too early re. the tarball. 
If you figure out how to modify the install script to build from source it could be helpful to keep always up-to-date and testing.

**Comment by jayrockk** [comment]
> edit: sorry commented too early re. the tarball. If you figure out how to modify the install script to build from source it could be helpful to keep always up-to-date and testing.

Well that's the thing. https://github.com/ZmnSCPxj/clboss/releases/download/v011C/clboss-v011C.tar.gz does not exist. And honestly I don't have the capacity to troubleshoot the clboss install script. I guess it is what it is.

**Comment by Grov-r** [comment]
Any way to get on the latest release with blitz while having the old release 1.0 installed?
could really do with the reduced channel rebalancing.

**Comment by openoms** [comment]
@jayrockk note that there is no 0.11C yet and the link to the tarvall 0.11B is lacking the `v`-s in the path and filename:  https://github.com/ZmnSCPxj/clboss/releases/download/0.11B/clboss-0.11B.tar.gz

@Grov-r not sure what you mean. You can switch between different CLBOSS versions by changing the binary in `/home/bitcoin/cl-plugins-available/` which is symlinked into the directory `/home/bitcoin/cl-plugins-enabled/`. You can only run one version of CLBOSS at a time but it's database is compatible between the different versions.

**Comment by jayrockk** [comment]
> @jayrockk note that there is no 0.11C yet and the link to the tarvall 0.11B is lacking the `v`-s in the path and filename: https://github.com/ZmnSCPxj/clboss/releases/download/0.11B/clboss-0.11B.tar.gz

@openoms
Thanks, got it. What are the chances to have a 0.11C tarball any time soon?

**Comment by jayrockk** [comment]
> Any way to get on the latest release with blitz while having the old release 1.0 installed?
> could really do with the reduced channel rebalancing.

@Grov-r

Just reinstalled 0.11B on Raspiblitz 1.7.2. It still works great, and there is less rebalancing.

Methods to install:
- configure & make, add symlink manually, OR
- change the install script to pull 0.11B, and install via Raspiblitz menu

I've tested both, and both work fine.

**Comment by ZmnSCPxj** [comment]
Well, I was dumb.  I made a 0.11C tag with full intent to make a release, but it looks like I actually forgot to, you know, actually release it.

There is a 0.11D now, which should work.

**Comment by openoms** [comment]
@ZmnSCPxj  thank you for tagging 0.11D, I have recorded the short instructions to update on the raspiblitz here: https://github.com/rootzoll/raspiblitz/issues/3072#issue-1214095317

I have two questions regarding the release:
* It is still labeled as a `pre-release`, is it mean to be the final?
* the previous release was labelled with a leading `v` as `v0.10`. This affects the download link for the release. Are you planning `v0.11` as the final? (sorry for the nit-picking)

**Comment by jayrockk** [comment]
> Well, I was dumb. I made a 0.11C tag with full intent to make a release, but it looks like I actually forgot to, you know, actually release it.
> 
> There is a 0.11D now, which should work.

Thanks, I will test it asap.

**Comment by ZmnSCPxj** [comment]
0.12 will be the next full release, tagged with `0.12` because why not.  Or maybe I will jsut tag `v0.12` too.  Odd numbers are pre-release, even are full release, letters only exist on odd numbers.

0.11D has a bug (see #101) so maybe 0.11E, which should release in a short while, assuming no other bugs on 0.11D are discovered.

**Comment by ZmnSCPxj** [comment]
Since there are regular tarballs now for 0.12, will close.
