### ISSUE TITLE
libev check broken

### ISSUE THREAD

**Issue by fiatjaf** [ksedgwic/clboss#92]
`./configure` is saying I need libev >= 4, but I have it:

```
./configure: line 13376: syntax error near unexpected token `libev,'
./configure: line 13376: `              PKG_CHECK_MODULES(libev, libev >= 4.0, :, :)'
```

![2022-01-08-075426_700x628_scrot](https://user-images.githubusercontent.com/1653275/148641546-2d167eac-4bec-4c1b-9573-9f5c53d8aa41.png)

**Comment by hoplaaa** [comment]
This is a syntax error.

I would try to restart the installation :  
`make clean` can help to clean previous builds.
`autoreconf -f -i` can rebuild your `configure` file.
https://github.com/ZmnSCPxj/clboss#installing

**Comment by fiatjaf** [comment]
Didn't work.

**Comment by ZmnSCPxj** [comment]
Did you attempt this on a git checkout?  If so, you might not have the `autoconf-archive`, which is what contains `PKG_CHECK_MODULES`.

In properly generated `configure` there is no line with `PKG_CHECK_MODULES`, as that should only exist in `configure.ac` and be translated if you have `autoconf-archive` installed.

**Comment by fiatjaf** [comment]
Yes, I tried it on a git checkout, and I tried the autoconf thing as there was no `configure` file.

**Comment by fiatjaf** [comment]
Next time I will try downloading an archive from a release.

**Comment by ZmnSCPxj** [comment]
Looking again, `PKG_CHECK_MODULES` is installed as part of `pkg-config`, not `autoconf-archive`, at least on Debian.

Do note that `README.md` lists `pkg-config` as a dependency, so still not a bug. https://github.com/ZmnSCPxj/clboss#dependencies

What OS are you using?  If you are referring to `apt` it seems to be some Debian derivative, and if so the list of package names in the `README` under "Dependencies" should install everything you need.

**Comment by fiatjaf** [comment]
That was it. Installing `pkg-config` fixed it. Sorry for the trouble.
