### ISSUE TITLE
load avg is high during clboss scanning peers

### ISSUE THREAD

**Issue by btweenthebars** [ksedgwic/clboss#94]
I notice my load avg spike for 5-10 minutes while clboss performs the regular peer scanning. During the time I see the topology process occupies the entire machine. It's very slow even trying to talk to lightningd rpc when this happens. So I wonder if it could cause forwarding to fail/delay rendering my node to be unreliable to my peers' eyes. My rig is an old i7 laptop, 8G ram, a little over 100 channels. I feel the scanning finished quicker when I had less peer. Does the scanning run every X minutes or it picks the time when less traffic to run ? I feel it runs pretty often and the operation should be less expensive. I can't imagine a raspiblitz node can go on with this.

**Comment by btweenthebars** [comment]
I'm looking at the source code trying to find a way to configure how often this scanning to run. For my node I think 4 times a day is enough, preferably at night. I've run into some force closes lately, idk maybe, it happened during the long scanning.

**Comment by JaviLib** [comment]
Same problem here with an i7 16Gb of RAM, topology process consumes an inmense amount of power only when clboss is enabled.

**Comment by svewa** [comment]
same here, and it uses up to 12GB of RAM, which would break it for those RaspberryPi users. My node has ~180 peers, but I don't know if that matters.

**Comment by JaviLib** [comment]
I have found a workaround to improve drastically the amount of time that the process uses by doing this modification in these 2 databases.

Stop the `lightningd` daemon, and go to the `lightningd` bitcoin directory and use the command `sqlite3 data.clboss` and repeat the same with `sqlite3 lightningd.sqlite3`:

```
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> PRAGMA page_size;
4096
sqlite> PRAGMA default_cache_size=65535;
sqlite> vacuum;
sqlite> pragma optimize;
sqlite> PRAGMA TEMP_STORE=2;
sqlite> PRAGMA SYNCHRONOUS=1;
sqlite> PRAGMA LOCKING_MODE=EXCLUSIVE;
```
You can use `ctrl-d` to exit the program, and you can start `lightningd` again when you have finished with the 2 databases.

In my computer, it only takes around 3 minutes of processing, but before it could take more than half an hour or even hours of wasting CPU cicles and I/O.

**Comment by ZmnSCPxj** [comment]
Closing in favor of #100
