### ISSUE TITLE
Black list nodes

### ISSUE THREAD

**Issue by Grov-r** [ksedgwic/clboss#96]
Sorry to hop on this, but also, perhaps related to

https://github.com/ZmnSCPxj/clboss/issues/95

There are some nodes that i would rather not connect to in the future, but me and the boss dont discriminate in the same way :)

ex
There are some nodes that impose a very high to-self-delay for return of funds on close
One node in particular had a delay of 1500+  that was over 2 weeks of delay, and i prefer not to connect to such a node, and i would never do it, but CLBOSS would.

SO in this example, if I could give a list of nodes i prefer not to connect to, it would be better, because i'm not sure there is a way to find out what the node would impose on to-self-delay before actually opening a channel and finding out the hard way.

**Comment by GhostTyper** [comment]
I assume you can use:

    lightning-cli clboss-unmanage ${NODEID} open

for every node you want to exclude.

**Comment by robinvonmises** [comment]
![image](https://user-images.githubusercontent.com/70470874/156435024-d90482fc-748f-47c4-958a-bd245ac4b414.png)

clboss-unmanage is not working for me :/ can somebody help?

I am running c-lightning on a RaspiBlitz 1.7.2

**Comment by lar-mar** [comment]
> ![image](https://user-images.githubusercontent.com/70470874/156435024-d90482fc-748f-47c4-958a-bd245ac4b414.png)
> 
> clboss-unmanage is not working for me :/ can somebody help?
> 
> I am running c-lightning on a RaspiBlitz 1.7.2

same for me

**Comment by openoms** [comment]
@surenic and @lar-mar you are running the last stable release of CLBOSS https://github.com/ZmnSCPxj/clboss/releases/tag/v0.10 which doesn't have that command available.
See what you can use with:
```
lightning-cli help
```

**Comment by lar-mar** [comment]
@openoms 

Thank you for clarification.

**Comment by ZmnSCPxj** [comment]
0.12 has been released with `clboss-unmanage`.  Closing.
