### ISSUE TITLE
Earnings report

### ISSUE THREAD

**Issue by http402** [ksedgwic/clboss#99]
i appreciate the idea of not having to look at my lightning node thx to automated managment, but how do i track earnings? i have RTL running but that doesn't give enough information. manually tracking the nodes balance i see it going up but also down over time. is there a command to export all data regarding fees earned and paid into CSV or some format that i can use to do my accounting?

**Comment by svewa** [comment]
`lightning-cli clboss-status` has the basic information

https://gist.github.com/johnongit/97f3b03599b80e02ef37d154ece7323e sums it up nicely, how much did you spend and how much did you earn.....

**Comment by ghost** [comment]
Could somebody of you fork this script to make it executable even without having Docker installed?

**Comment by willcl-ark** [comment]
> Could somebody of you fork this script to make it executable even without having Docker installed?

I didn't try the script, but just looks like to me you'd change line 8 from:
```
JSON=`docker exec cln lightning-cli clboss-status | jq .offchain_earnings_tracker`
```
to
```
JSON=`lightning-cli clboss-status | jq .offchain_earnings_tracker`
```
and it should work

**Comment by ghost** [comment]
Thanks a lot! That actually helped. 
Unfortunately, I still get  an error. Under my Raspiblitz installation within the admin directory it says:
`lightning-cli: Moving into '/home/admin/.lightning/bitcoin': No such file or directory`

**Comment by willcl-ark** [comment]
Oh well you'll need to set the BASEDIR directory variable properly. Perhaps @openoms can help with what it should be for the blitz

**Comment by openoms** [comment]
@BlueBallroom is wolking in admin, but CLN and CLBOSS is running with the bitcoin user.
Switch to it and the default directory will work.

**Comment by ghost** [comment]
@openoms @willcl-ark thanks again for your support! 
After some twisting it now works great. I created a repository for everyone else to contribute:
https://github.com/BlueBallroom/CLN-Earning-Script-Raspiblitz

**Comment by ksedgwic** [comment]
closing
